import CentralData from './context'
import './globals.css'


export const metadata = {
  title: 'UnSplash App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
		<html lang="en">
			<head>
				<link
					rel="icon"
					type="image/png"
					href="https://imgd-ct.aeplcdn.com/1280x720/n/37ak3sa_1483591.jpg?q=75"
				/>
			</head>
			<body suppressHydrationWarning>
				<CentralData>{children}</CentralData>
			</body>	
		</html>
	);
}
